// India States / Union Territories with their cities & district headquarters.
// Used by the Dealer Registration form for the State -> City cascading dropdowns.
// Generated from open datasets (nshntarora/Indian-Cities-JSON + sab99r/Indian-States-And-Districts),
// normalized to the 36 States/UTs, deduped and sorted. 1671 cities total.

export interface StateCities {
  state: string;
  cities: string[];
}

export const INDIA_STATES_CITIES: StateCities[] = [
  { state: "Andhra Pradesh", cities: ["Adoni", "Amalapuram", "Anakapalle", "Anantapur", "Bapatla", "Bheemunipatnam", "Bhimavaram", "Bobbili", "Chilakaluripet", "Chirala", "Chittoor", "Dharmavaram", "East Godavari", "Eluru", "Gooty", "Gudivada", "Gudur", "Guntakal", "Guntur", "Hindupur", "Jaggaiahpet", "Jammalamadugu", "Kadapa", "Kadiri", "Kakinada", "Kandukur", "Kavali", "Kovvur", "Krishna", "Kurnool", "Macherla", "Machilipatnam", "Madanapalle", "Mandapeta", "Markapur", "Nagari", "Naidupet", "Nandyal", "Narasapuram", "Narasaraopet", "Narsipatnam", "Nellore", "Nidadavole", "Nuzvid", "Ongole", "Palacole", "Palasa Kasibugga", "Parvathipuram", "Pedana", "Peddapuram", "Pithapuram", "Ponnur", "Prakasam", "Proddatur", "Punganur", "Puttur", "Rajahmundry", "Rajam", "Rajampet", "Ramachandrapuram", "Rayachoti", "Rayadurg", "Renigunta", "Repalle", "Salur", "Samalkot", "Sattenapalle", "Srikakulam", "Srikalahasti", "Srisailam Project (Right Flank Colony) Township", "Sullurpeta", "Tadepalligudem", "Tadpatri", "Tanuku", "Tenali", "Tirupati", "Tiruvuru", "Tuni", "Uravakonda", "Venkatagiri", "Vijayawada", "Vinukonda", "Visakhapatnam", "Vizianagaram", "West Godavari", "Yemmiganur", "Yerraguntla", "YSR Kadapa"] },
  { state: "Arunachal Pradesh", cities: ["Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Kra Daadi", "Kurung Kumey", "Lohit", "Longding", "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Naharlagun", "Namsai", "Papum Pare", "Pasighat", "Siang", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang"] },
  { state: "Assam", cities: ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Bongaigaon City", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Diphu", "Dispur", "Goalpara", "Golaghat", "Guwahati", "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Lanka", "Lumding", "Majuli", "Mangaldoi", "Mankachar", "Margherita", "Mariani", "Marigaon", "Morigaon", "Nagaon", "Nalbari", "North Lakhimpur", "Rangia", "Sibsagar", "Silapathar", "Silchar", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tezpur", "Tinsukia", "Udalguri", "West Karbi Anglong"] },
  { state: "Bihar", cities: ["Araria", "Arrah", "Arwal", "Asarganj", "Aurangabad", "Bagaha", "Banka", "Barh", "Begusarai", "Bettiah", "Bhagalpur", "Bhojpur", "Buxar", "Chhapra", "Darbhanga", "Dehri-on-Sone", "Dumraon", "East Champaran (Motihari)", "Forbesganj", "Gaya", "Gopalganj", "Hajipur", "Jamalpur", "Jamui", "Jehanabad", "Kaimur (Bhabua)", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Lalganj", "Madhepura", "Madhubani", "Maharajganj", "Mahnar Bazar", "Makhdumpur", "Maner", "Manihari", "Marhaura", "Masaurhi", "Mirganj", "Mokameh", "Motihari", "Motipur", "Munger", "Munger (Monghyr)", "Murliganj", "Muzaffarpur", "Nalanda", "Narkatiaganj", "Naugachhia", "Nawada", "Nokha", "Patna", "Piro", "Purnia", "Purnia (Purnea)", "Rafiganj", "Rajgir", "Ramnagar", "Raxaul Bazar", "Revelganj", "Rohtas", "Rosera", "Saharsa", "Samastipur", "Saran", "Sasaram", "Sheikhpura", "Sheohar", "Sherghati", "Silao", "Sitamarhi", "Siwan", "Sonepur", "Sugauli", "Sultanganj", "Supaul", "Vaishali", "Warisaliganj", "West Champaran"] },
  { state: "Chhattisgarh", cities: ["Ambikapur", "Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bhatapara", "Bhilai Nagar", "Bijapur", "Bilaspur", "Chirmiri", "Dalli-Rajhara", "Dantewada (South Bastar)", "Dhamtari", "Durg", "Gariyaband", "Jagdalpur", "Janjgir-Champa", "Jashpur", "Kabirdham (Kawardha)", "Kanker (North Bastar)", "Kondagaon", "Korba", "Korea (Koriya)", "Mahasamund", "Manendragarh", "Mungeli", "Naila Janjgir", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Sakti", "Sukma", "Surajpur", "Surguja", "Tilda Newra"] },
  { state: "Goa", cities: ["Bicholim", "Calangute", "Canacona", "Candolim", "Cuncolim", "Curchorem", "Mapusa", "Margao", "Marmagao", "North Goa", "Panaji", "Pernem", "Ponda", "Quepem", "Sanguem", "Sanquelim", "South Goa", "Valpoi", "Vasco da Gama"] },
  { state: "Gujarat", cities: ["Adalaj", "Ahmedabad", "Amreli", "Anand", "Anjar", "Ankleshwar", "Aravalli", "Banaskantha (Palanpur)", "Bharuch", "Bhavnagar", "Bhuj", "Botad", "Chhapra", "Chhota Udepur", "Dahod", "Dangs (Ahwa)", "Deesa", "Devbhoomi Dwarka", "Dhoraji", "Gandhinagar", "Gir Somnath", "Godhra", "Jamnagar", "Junagadh", "Kachchh", "Kadi", "Kapadvanj", "Keshod", "Khambhat", "Kheda (Nadiad)", "Lathi", "Limbdi", "Lunawada", "Mahemdabad", "Mahesana", "Mahisagar", "Mahuva", "Manavadar", "Mandvi", "Mangrol", "Mansa", "Mehsana", "Modasa", "Morbi", "Morvi", "Nadiad", "Narmada (Rajpipla)", "Navsari", "Padra", "Palanpur", "Palitana", "Panchmahal (Godhra)", "Pardi", "Patan", "Petlad", "Porbandar", "Radhanpur", "Rajkot", "Rajpipla", "Rajula", "Ranavav", "Rapar", "Sabarkantha (Himmatnagar)", "Salaya", "Sanand", "Savarkundla", "Sidhpur", "Sihor", "Songadh", "Surat", "Surendranagar", "Talaja", "Tapi (Vyara)", "Thangadh", "Tharad", "Umbergaon", "Umreth", "Una", "Unjha", "Upleta", "Vadnagar", "Vadodara", "Valsad", "Vapi", "Veraval", "Vijapur", "Viramgam", "Visnagar", "Vyara", "Wadhwan", "Wankaner"] },
  { state: "Haryana", cities: ["Ambala", "Bahadurgarh", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gohana", "Gurgaon", "Hansi", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Ladwa", "Mahendragarh", "Mandi Dabwali", "Mewat", "Narnaul", "Narwana", "Palwal", "Panchkula", "Panipat", "Pehowa", "Pinjore", "Rania", "Ratia", "Rewari", "Rohtak", "Safidon", "Samalkha", "Sarsod", "Shahbad", "Sirsa", "Sohna", "Sonipat", "Taraori", "Thanesar", "Tohana", "Yamunanagar"] },
  { state: "Himachal Pradesh", cities: ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul & Spiti", "Manali", "Mandi", "Nahan", "Palampur", "Shimla", "Sirmaur (Sirmour)", "Solan", "Sundarnagar", "Una"] },
  { state: "Jharkhand", cities: ["Adityapur", "Bokaro", "Bokaro Steel City", "Chaibasa", "Chatra", "Chirkunda", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumia", "Gumla", "Hazaribag", "Jamshedpur", "Jamtara", "Jhumri Tilaiya", "Khunti", "Koderma", "Latehar", "Lohardaga", "Madhupur", "Medininagar (Daltonganj)", "Mihijam", "Musabani", "Pakaur", "Pakur", "Palamu", "Patratu", "Phusro", "Ramgarh", "Ranchi", "Sahibganj", "Saunda", "Seraikela-Kharsawan", "Simdega", "Tenu dam-cum-Kathhara", "West Singhbhum"] },
  { state: "Karnataka", cities: ["Adyar", "Afzalpur", "Arsikere", "Athni", "Bagalkot", "Ballari", "Ballari (Bellary)", "Belagavi", "Belagavi (Belgaum)", "Bengaluru", "Bengaluru (Bangalore) Rural", "Bengaluru (Bangalore) Urban", "Bidar", "Chamarajanagar", "Chikballapur", "Chikkamagaluru", "Chikkamagaluru (Chikmagalur)", "Chitradurga", "Dakshina Kannada", "Davanagere", "Davangere", "Dharwad", "Gadag", "Gokak", "Hassan", "Haveri", "Hubli-Dharwad", "Kalaburagi (Gulbarga)", "Karwar", "Kodagu", "Kolar", "Koppal", "Lakshmeshwar", "Lingsugur", "Maddur", "Madhugiri", "Madikeri", "Magadi", "Mahalingapura", "Malavalli", "Malur", "Mandya", "Mangaluru", "Manvi", "Mudabidri", "Mudalagi", "Muddebihal", "Mudhol", "Mulbagal", "Mundargi", "Mysore", "Mysuru (Mysore)", "Nanjangud", "Nargund", "Navalgund", "Nelamangala", "Pavagada", "Piriyapatna", "Puttur", "Raayachuru", "Rabkavi Banhatti", "Raichur", "Ramanagara", "Ramanagaram", "Ramdurg", "Ranebennuru", "Ranibennur", "Robertson Pet", "Ron", "Sadalagi", "Sagara", "Sakaleshapura", "Sanduru", "Sankeshwara", "Saundatti-Yellamma", "Savanur", "Sedam", "Shahabad", "Shahpur", "Shiggaon", "Shikaripur", "Shivamogga", "Shivamogga (Shimoga)", "Shrirangapattana", "Sidlaghatta", "Sindagi", "Sindhagi", "Sindhnur", "Sira", "Sirsi", "Siruguppa", "Srinivaspur", "Surapura", "Talikota", "Tarikere", "Tekkalakote", "Terdal", "Tiptur", "Tumakuru (Tumkur)", "Tumkur", "Udupi", "Uttara Kannada (Karwar)", "Vijayapura", "Vijayapura (Bijapur)", "Wadi", "Yadgir"] },
  { state: "Kerala", cities: ["Adoor", "Alappuzha", "Attingal", "Chalakudy", "Changanassery", "Cherthala", "Chittur-Thathamangalam", "Ernakulam", "Guruvayoor", "Idukki", "Kanhangad", "Kannur", "Kasaragod", "Kayamkulam", "Kochi", "Kodungallur", "Kollam", "Kottayam", "Koyilandy", "Kozhikode", "Kunnamkulam", "Malappuram", "Mattannur", "Mavelikkara", "Mavoor", "Muvattupuzha", "Nedumangad", "Neyyattinkara", "Nilambur", "Ottappalam", "Palai", "Palakkad", "Panamattom", "Panniyannur", "Pappinisseri", "Paravoor", "Pathanamthitta", "Peringathur", "Perinthalmanna", "Perumbavoor", "Ponnani", "Punalur", "Puthuppally", "Shoranur", "Taliparamba", "Thiruvalla", "Thiruvananthapuram", "Thodupuzha", "Thrissur", "Tirur", "Vaikom", "Varkala", "Vatakara", "Wayanad"] },
  { state: "Madhya Pradesh", cities: ["Agar Malwa", "Alirajpur", "Anuppur", "Ashok Nagar", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Ganjbasoda", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Itarsi", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Lahar", "Maharajpur", "Mahidpur", "Maihar", "Malaj Khand", "Manasa", "Manawar", "Mandideep", "Mandla", "Mandsaur", "Mauganj", "Mhow Cantonment", "Mhowgaon", "Morena", "Multai", "Mundi", "Murwara (Katni)", "Nagda", "Nainpur", "Narsinghgarh", "Narsinghpur", "Neemuch", "Nepanagar", "Niwari", "Nowgong", "Nowrozabad (Khodargama)", "Pachore", "Pali", "Panagar", "Pandhurna", "Panna", "Pasan", "Pipariya", "Pithampur", "Porsa", "Prithvipur", "Raghogarh-Vijaypur", "Rahatgarh", "Raisen", "Rajgarh", "Ratlam", "Rau", "Rehli", "Rewa", "Sabalgarh", "Sagar", "Sanawad", "Sarangpur", "Sarni", "Satna", "Sausar", "Sehore", "Sendhwa", "Seoni", "Seoni-Malwa", "Shahdol", "Shajapur", "Shamgarh", "Sheopur", "Shivpuri", "Shujalpur", "Sidhi", "Sihora", "Singrauli", "Sironj", "Sohagpur", "Tarana", "Tikamgarh", "Ujjain", "Umaria", "Vidisha", "Vijaypur", "Wara Seoni"] },
  { state: "Maharashtra", cities: ["Achalpur", "Ahmednagar", "Akola", "Akot", "Amalner", "Ambejogai", "Amravati", "Anjangaon", "Arvi", "Aurangabad", "Beed", "Bhandara", "Bhiwandi", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Ichalkaranji", "Jalgaon", "Jalna", "Kalyan-Dombivali", "Karjat", "Kolhapur", "Latur", "Loha", "Lonar", "Lonavla", "Mahad", "Malegaon", "Malkapur", "Mangalvedhe", "Mangrulpir", "Manjlegaon", "Manmad", "Manwath", "Mehkar", "Mhaswad", "Mira-Bhayandar", "Morshi", "Mukhed", "Mul", "Mumbai", "Mumbai City", "Mumbai Suburban", "Murtijapur", "Nagpur", "Nanded", "Nanded-Waghala", "Nandgaon", "Nandura", "Nandurbar", "Narkhed", "Nashik", "Nawapur", "Nilanga", "Osmanabad", "Ozar", "Pachora", "Paithan", "Palghar", "Pandharkaoda", "Pandharpur", "Panvel", "Parbhani", "Parli", "Partur", "Pathardi", "Pathri", "Patur", "Pauni", "Pen", "Phaltan", "Pulgaon", "Pune", "Purna", "Pusad", "Rahuri", "Raigad", "Rajura", "Ramtek", "Ratnagiri", "Raver", "Risod", "Sailu", "Sangamner", "Sangli", "Sangole", "Sasvad", "Satana", "Satara", "Savner", "Sawantwadi", "Shahade", "Shegaon", "Shendurjana", "Shirdi", "Shirpur-Warwade", "Shirur", "Shrigonda", "Shrirampur", "Sillod", "Sindhudurg", "Sinnar", "Solapur", "Soyagaon", "Talegaon Dabhade", "Talode", "Tasgaon", "Thane", "Tirora", "Tuljapur", "Tumsar", "Uchgaon", "Udgir", "Umarga", "Umarkhed", "Umred", "Uran", "Uran Islampur", "Vadgaon Kasba", "Vaijapur", "Vasai-Virar", "Vita", "Wadgaon Road", "Wai", "Wani", "Wardha", "Warora", "Warud", "Washim", "Yavatmal", "Yawal", "Yevla"] },
  { state: "Manipur", cities: ["Bishnupur", "Chandel", "Churachandpur", "Imphal", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Lilong", "Mayang Imphal", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"] },
  { state: "Meghalaya", cities: ["East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "Nongstoin", "North Garo Hills", "Ri Bhoi", "Shillong", "South Garo Hills", "South West Garo Hills", "South West Khasi Hills", "Tura", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"] },
  { state: "Mizoram", cities: ["Aizawl", "Champhai", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip"] },
  { state: "Nagaland", cities: ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"] },
  { state: "Odisha", cities: ["Angul", "Balangir", "Balasore", "Baleshwar Town", "Barbil", "Bargarh", "Baripada Town", "Bhadrak", "Bhawanipatna", "Bhubaneswar", "Boudh", "Brahmapur", "Byasanagar", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghapur", "Jajpur", "Jatani", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Kendujhar (Keonjhar)", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangapur", "Nabarangpur", "Nayagarh", "Nuapada", "Paradip", "Parlakhemundi", "Pattamundai", "Phulabani", "Puri", "Rairangpur", "Rajagangapur", "Raurkela", "Rayagada", "Sambalpur", "Sonepur", "Soro", "Sunabeda", "Sundargarh", "Talcher", "Tarbha", "Titlagarh"] },
  { state: "Punjab", cities: ["Amritsar", "Barnala", "Batala", "Bathinda", "Dhuri", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Firozpur", "Firozpur Cantt.", "Gobindgarh", "Gurdaspur", "Hoshiarpur", "Jagraon", "Jalandhar", "Jalandhar Cantt.", "Kapurthala", "Khanna", "Kharar", "Kot Kapura", "Longowal", "Ludhiana", "Malerkotla", "Malout", "Mansa", "Moga", "Mohali", "Morinda, India", "Mukerian", "Muktsar", "Nabha", "Nakodar", "Nangal", "Nawanshahr", "Nawanshahr (Shahid Bhagat Singh Nagar)", "Pathankot", "Patiala", "Patti", "Pattran", "Phagwara", "Phillaur", "Qadian", "Raikot", "Rajpura", "Rampura Phul", "Rupnagar", "Sahibzada Ajit Singh Nagar (Mohali)", "Samana", "Sangrur", "Sirhind Fatehgarh Sahib", "Sujanpur", "Sunam", "Talwara", "Tarn Taran", "Urmar Tanda", "Zira", "Zirakpur"] },
  { state: "Rajasthan", cities: ["Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Lachhmangarh", "Ladnu", "Lakheri", "Lalsot", "Losal", "Makrana", "Malpura", "Mandalgarh", "Mandawa", "Mangrol", "Merta City", "Mount Abu", "Nadbai", "Nagar", "Nagaur", "Nasirabad", "Nathdwara", "Neem-Ka-Thana", "Nimbahera", "Nohar", "Nokha", "Pali", "Phalodi", "Phulera", "Pilani", "Pilibanga", "Pindwara", "Pipar City", "Prantij", "Pratapgarh", "Raisinghnagar", "Rajakhera", "Rajaldesar", "Rajgarh (Alwar)", "Rajgarh (Churu)", "Rajsamand", "Ramganj Mandi", "Ramngarh", "Ratangarh", "Rawatbhata", "Rawatsar", "Reengus", "Sadri", "Sadulpur", "Sadulshahar", "Sagwara", "Sambhar", "Sanchore", "Sangaria", "Sardarshahar", "Sawai Madhopur", "Shahpura", "Sheoganj", "Sikar", "Sirohi", "Sojat", "Sri Ganganagar", "Sri Madhopur", "Sujangarh", "Sumerpur", "Suratgarh", "Takhatgarh", "Taranagar", "Todabhim", "Todaraisingh", "Tonk", "Udaipur", "Udaipurwati", "Vijainagar, Ajmer"] },
  { state: "Sikkim", cities: ["East Sikkim", "Gangtok", "Gyalshing", "Jorethang", "Mangan", "Namchi", "North Sikkim", "Rangpo", "Ravangla", "Singtam", "South Sikkim", "West Sikkim"] },
  { state: "Tamil Nadu", cities: ["Arakkonam", "Ariyalur", "Aruppukkottai", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Gobichettipalayam", "Kancheepuram", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Lalgudi", "Madurai", "Manachanallur", "Nagapattinam", "Nagercoil", "Namagiripettai", "Namakkal", "Nandivaram-Guduvancheri", "Nanjikottai", "Natham", "Nellikuppam", "Neyveli (TS)", "Nilgiris", "O' Valley", "Oddanchatram", "P.N.Patti", "Pacode", "Padmanabhapuram", "Palani", "Palladam", "Pallapatti", "Pallikonda", "Panagudi", "Panruti", "Paramakudi", "Parangipettai", "Pattukkottai", "Perambalur", "Peravurani", "Periyakulam", "Periyasemur", "Pernampattu", "Pollachi", "Polur", "Ponneri", "Pudukkottai", "Pudupattinam", "Puliyankudi", "Punjaipugalur", "Rajapalayam", "Ramanathapuram", "Rameshwaram", "Ranipet", "Rasipuram", "Salem", "Sankarankovil", "Sankari", "Sathyamangalam", "Sattur", "Shenkottai", "Sholavandan", "Sholingur", "Sirkali", "Sivaganga", "Sivagiri", "Sivakasi", "Srivilliputhur", "Surandai", "Suriyampalayam", "Tenkasi", "Thammampatti", "Thanjavur", "Tharamangalam", "Tharangambadi", "Theni", "Theni Allinagaram", "Thirumangalam", "Thirupuvanam", "Thiruthuraipoondi", "Thiruvallur", "Thiruvarur", "Thoothukudi (Tuticorin)", "Thuraiyur", "Tindivanam", "Tiruchendur", "Tiruchengode", "Tiruchirappalli", "Tirukalukundram", "Tirukkoyilur", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruttani", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Tiruvethipuram", "Tittakudi", "Udhagamandalam", "Udumalaipettai", "Unnamalaikadai", "Usilampatti", "Uthamapalayam", "Uthiramerur", "Vadakkuvalliyur", "Vadalur", "Vadipatti", "Valparai", "Vandavasi", "Vaniyambadi", "Vedaranyam", "Vellakoil", "Vellore", "Vikramasingapuram", "Viluppuram", "Virudhachalam", "Virudhunagar", "Viswanatham"] },
  { state: "Telangana", cities: ["Adilabad", "Bellampalle", "Bhadrachalam", "Bhadradri Kothagudem", "Bhainsa", "Bhongir", "Bodhan", "Farooqnagar", "Gadwal", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhoopalpally", "Jogulamba Gadwal", "Kagaznagar", "Kamareddy", "Karimnagar", "Khammam", "Komaram Bheem Asifabad", "Koratla", "Kothagudem", "Kyathampalle", "Mahabubabad", "Mahabubnagar", "Mahbubnagar", "Mancherial", "Mandamarri", "Manuguru", "Medak", "Medchal", "Miryalaguda", "Nagarkurnool", "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Palwancha", "Peddapalli", "Rajanna Sircilla", "Ramagundam", "Rangareddy", "Sadasivpet", "Sangareddy", "Siddipet", "Sircilla", "Suryapet", "Tandur", "Vikarabad", "Wanaparthy", "Warangal", "Warangal (Rural)", "Warangal (Urban)", "Yadadri Bhuvanagiri", "Yellandu"] },
  { state: "Tripura", cities: ["Agartala", "Belonia", "Dhalai", "Dharmanagar", "Gomati", "Kailasahar", "Khowai", "North Tripura", "Pratapgarh", "Sepahijala", "South Tripura", "Udaipur", "Unakoti", "West Tripura"] },
  { state: "Uttar Pradesh", cities: ["Achhnera", "Agra", "Aligarh", "Allahabad", "Ambedkar Nagar", "Amethi (Chatrapati Sahuji Mahraj Nagar)", "Amroha", "Amroha (J.P. Nagar)", "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chandausi", "Chitrakoot", "Deoria", "Etah", "Etawah", "Faizabad", "Farrukhabad", "Fatehpur", "Fatehpur Sikri", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hapur (Panchsheel Nagar)", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kalpi", "Kannauj", "Kanpur", "Kanpur Dehat", "Kanpur Nagar", "Kanshiram Nagar (Kasganj)", "Kaushambi", "Khair", "Kushinagar (Padrauna)", "Laharpur", "Lakhimpur", "Lakhimpur - Kheri", "Lal Gopalganj Nindaura", "Lalganj", "Lalitpur", "Lar", "Loni", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Modinagar", "Moradabad", "Muzaffarnagar", "Nagina", "Najibabad", "Nakur", "Nanpara", "Naraura", "Naugawan Sadat", "Nautanwa", "Nawabganj", "Nehtaur", "Niwai", "Noida", "Noorpur", "Obra", "Orai", "Padrauna", "Palia Kalan", "Parasi", "Phulpur", "Pihani", "Pilibhit", "Pilkhuwa", "Powayan", "Pratapgarh", "Pukhrayan", "Puranpur", "Purwa", "Rae Bareli", "RaeBareli", "Rampur", "Rampur Maniharan", "Rasra", "Rath", "Renukoot", "Reoti", "Robertsganj", "Rudauli", "Rudrapur", "Sadabad", "Safipur", "Saharanpur", "Sahaspur", "Sahaswan", "Sahawar", "Sahjanwa", "Saidpur", "Sambhal", "Sambhal (Bhim Nagar)", "Samdhan", "Samthar", "Sandi", "Sandila", "Sant Kabir Nagar", "Sardhana", "Seohara", "Shahabad, Hardoi", "Shahabad, Rampur", "Shahganj", "Shahjahanpur", "Shamali (Prabuddh Nagar)", "Shamli", "Shamsabad, Agra", "Shamsabad, Farrukhabad", "Sherkot", "Shikarpur, Bulandshahr", "Shikohabad", "Shishgarh", "Shravasti", "Siana", "Siddharth Nagar", "Sikanderpur", "Sikandra Rao", "Sikandrabad", "Sirsaganj", "Sirsi", "Sitapur", "Sonbhadra", "Soron", "Sultanpur", "Sumerpur", "Tanda", "Thakurdwara", "Thana Bhawan", "Tilhar", "Tirwaganj", "Tulsipur", "Tundla", "Ujhani", "Unnao", "Utraula", "Varanasi", "Vrindavan", "Warhapur", "Zaidpur", "Zamania"] },
  { state: "Uttarakhand", cities: ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haldwani-cum-Kathgodam", "Hardwar", "Haridwar", "Kashipur", "Manglaur", "Mussoorie", "Nagla", "Nainital", "Pauri", "Pauri Garhwal", "Pithoragarh", "Ramnagar", "Rishikesh", "Roorkee", "Rudraprayag", "Rudrapur", "Sitarganj", "Srinagar", "Tehri", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"] },
  { state: "West Bengal", cities: ["Adra", "Alipurduar", "Arambagh", "Asansol", "Baharampur", "Balurghat", "Bankura", "Birbhum", "Burdwan (Bardhaman)", "Cooch Behar", "Dakshin Dinajpur (South Dinajpur)", "Darjeeling", "Darjiling", "English Bazar", "Gangarampur", "Habra", "Hooghly", "Howrah", "Hugli-Chinsurah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kharagpur", "Kolkata", "Mainaguri", "Malda", "Mathabhanga", "Medinipur", "Memari", "Monoharpur", "Murshidabad", "Nabadwip", "Nadia", "Naihati", "North 24 Parganas", "Panchla", "Paschim Medinipur (West Medinipur)", "Paschim Punropara", "Purba Medinipur (East Medinipur)", "Purulia", "Raghunathganj", "Raghunathpur", "Raiganj", "Rampurhat", "Ranaghat", "Sainthia", "Santipur", "Siliguri", "Sonamukhi", "South 24 Parganas", "Srirampore", "Suri", "Taki", "Tamluk", "Tarakeswar", "Uttar Dinajpur (North Dinajpur)"] },
  { state: "Andaman and Nicobar Islands", cities: ["Bamboo Flat", "Campbell Bay", "Car Nicobar", "Diglipur", "Garacharma", "Havelock", "Hut Bay", "Little Andaman", "Mayabunder", "Neil Island", "Port Blair", "Rangat"] },
  { state: "Chandigarh", cities: ["Chandigarh"] },
  { state: "Dadra and Nagar Haveli and Daman and Diu", cities: ["Amli", "Dadra & Nagar Haveli", "Daman", "Diu", "Dudhani", "Khanvel", "Naroli", "Silvassa"] },
  { state: "Delhi", cities: ["Central Delhi", "Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"] },
  { state: "Jammu and Kashmir", cities: ["Anantnag", "Bandipore", "Baramula", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch", "Pulwama", "Punch", "Rajauri", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Sopore", "Srinagar", "Udhampur"] },
  { state: "Ladakh", cities: ["Diskit", "Drass", "Kargil", "Leh", "Nubra", "Zanskar"] },
  { state: "Lakshadweep", cities: ["Agatti", "Amini", "Androth", "Andrott", "Bithra", "Chethlath", "Kadmat", "Kadmath", "Kalpeni", "Kavaratti", "Kilthan", "Minicoy"] },
  { state: "Puducherry", cities: ["Karaikal", "Mahe", "Pondicherry", "Yanam"] }
];
